#!/bin/bash

fullfile=$1
filename=$(basename "$fullfile")
extension="${filename##*.}"
filename="${filename%.*}"

echo $filename
convert $fullfile -scale 5% -scale 1000% ${filename}_pixelated.${extension}
convert ${filename}_pixelated.${extension} -geometry 2560x1440^ -gravity center -crop 2560x1440+0+0 ${filename}_cropped.${extension}
